inherit_gem:
  relaxed-rubocop: .rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7.4
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimeters:
  EnforcedStyle: line_count_based

Layout/HashAligment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

RSpec/LetSetup:
  Enabled: false
