default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: bikeramp
  password: bikeramp

development:
  <<: *default
  database: bikeramp_development

test:
  <<: *default
  database: bikeramp_test


